### ISSUE TITLE
Adding Reorder/Delete functions to sections (multivalued section)

### ISSUE THREAD

**Issue by marbetschar** [Mandelkind/Eureka#1]
For original issue see https://github.com/xmartlabs/Eureka/issues/17

**Comment by mathmatrix828** [comment]
Right, so as to the trigger, try setting ```UILongGestureRecognizer``` up to trigger ```moveRowAtIndexPath:``` after editing is done

**Comment by marbetschar** [comment]
What do you mean exactly? I'm currently trying a different approach, which omits editing mode altogether if moving is triggered by using `UILongGestureRecognizer`.

This way we can allow for the default `tableView` editing buttons as well as supporting drag & drop by using the long press gesture.

**Comment by mathmatrix828** [comment]
Ok, I was slightly confused about how reordering worked apparently. I would have ```UILongGestureRecognizer``` trigger ```editRowAtIndexPath``` and then when it finishes, call ```UITableView moveRowAtIndexPath:toIndexPath:```

**Comment by marbetschar** [comment]
See https://github.com/Mandelkind/Eureka/commit/ac31109d6c65170c2d8750ea4d09c1eaa36fde34 for the new approach without touching editing state - this seems to work Ok for the `UILongGestureRecognizer`.

But if we can handle `UILongGestureRecognizer` and the `editingMode` at once, this would be awesome! Feel free to modify to get things going - I'll first have to get some hours of sleep ;)

**Comment by mathmatrix828** [comment]
😄 will do! I may look a little more into handling the slide action portion of things and how that all fits together as well

**Comment by marbetschar** [comment]
Sounds reasonable!

**Comment by marbetschar** [comment]
Sample Implementation:
https://github.com/FlorianMielke/FMMoveTableView

**Comment by prat0088** [comment]
This looks fantastic.  Will it be possible for it to use manual ordering with the traditional grab bars, too?

**Comment by marbetschar** [comment]
@prat0088 that's what we are aiming for ;)

Support the traditional edit mode for reordering as well as supporting the UILongPressGestureRecognizer.

**Comment by marbetschar** [comment]
Closed in favour of more granular issues:

- Reorder Rows: https://github.com/Mandelkind/Eureka/issues/3, https://github.com/Mandelkind/Eureka/issues/4
- Add Rows: https://github.com/Mandelkind/Eureka/issues/7, https://github.com/Mandelkind/Eureka/issues/8
- Delete Rows: https://github.com/Mandelkind/Eureka/issues/5, https://github.com/Mandelkind/Eureka/issues/6
- Section default values: https://github.com/Mandelkind/Eureka/issues/9
